spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: irctc-Provider-App
            uri: lb://IRCTC-Provider-App
            predicates:
            - Path=/irctc/**
server:
  port: 3333
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
