spring:
  application:
    name: MakeMyGrip-Consumer-App
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:9090
server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
